/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cycles
         * @description Fetches cycles using cursor-based pagination
         */
        get: {
            parameters: {
                query: {
                    /** @description Data inicial em Brasília (AAAA-MM-DD) */
                    start: string;
                    /** @description Data final inclusiva em Brasília (AAAA-MM-DD) */
                    end: string;
                    /** @description Cursor opaco da página anterior */
                    cursor?: string;
                    /** @description Number of records (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.CyclesPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get insights
         * @description Fetches daily strain and recovery from continuous aggregates for the last 30 days
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recoveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recoveries
         * @description Fetches recoveries using cursor-based pagination
         */
        get: {
            parameters: {
                query: {
                    /** @description Data inicial em Brasília (AAAA-MM-DD) */
                    start: string;
                    /** @description Data final inclusiva em Brasília (AAAA-MM-DD) */
                    end: string;
                    /** @description Cursor opaco da página anterior */
                    cursor?: string;
                    /** @description Number of records (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.RecoveriesPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sleeps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get sleeps
         * @description Fetches sleeps using cursor-based pagination
         */
        get: {
            parameters: {
                query: {
                    /** @description Data inicial em Brasília (AAAA-MM-DD) */
                    start: string;
                    /** @description Data final inclusiva em Brasília (AAAA-MM-DD) */
                    end: string;
                    /** @description Cursor opaco da página anterior */
                    cursor?: string;
                    /** @description Number of records (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.SleepsPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger ad-hoc sync
         * @description Enqueues a background sync job for the authenticated user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Too Many Requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar o estado persistido da sincronização */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.SyncStatusResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get basic profile info
         * @description Fetches the user profile from the WHOOP API
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get workouts
         * @description Fetches workouts using cursor-based pagination
         */
        get: {
            parameters: {
                query: {
                    /** @description Data inicial em Brasília (AAAA-MM-DD) */
                    start: string;
                    /** @description Data final inclusiva em Brasília (AAAA-MM-DD) */
                    end: string;
                    /** @description Cursor opaco da página anterior */
                    cursor?: string;
                    /** @description Number of records (default 50, max 200) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.WorkoutsPage"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_api.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_arvind_whoop-stats_internal_db.Cycle": {
            average_heart_rate: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            end_time: string | null;
            id: number;
            kilojoule: number | null;
            max_heart_rate: number | null;
            score_state: string | null;
            /** Format: date-time */
            start_time: string;
            step_count: number | null;
            strain: number | null;
            timezone_offset: Record<string, never> | null;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        "github_com_arvind_whoop-stats_internal_db.GetRecoveriesRow": {
            /** Format: date-time */
            created_at: string;
            cycle_end: string | null;
            cycle_start: string | null;
            hrv_rmssd_milli: number | null;
            id: number;
            /** Format: date-time */
            recorded_at: string;
            recovery_score: number | null;
            /** Format: date-time */
            reference_time: string | null;
            resting_heart_rate: number | null;
            score_state: string | null;
            skin_temp_celsius: number | null;
            sleep_id: string | null;
            spo2_percentage: number | null;
            /** Format: date-time */
            start_time: string;
            timezone_offset: Record<string, never> | null;
            /** Format: date-time */
            updated_at: string;
            user_calibrating: boolean | null;
            user_id: string;
        };
        "github_com_arvind_whoop-stats_internal_db.Sleep": {
            baseline_milli: number | null;
            /** Format: date-time */
            created_at: string;
            cycle_id: number | null;
            disturbance_count: number | null;
            /** Format: date-time */
            end_time: string | null;
            id: string;
            nap: boolean | null;
            need_from_recent_nap_milli: number | null;
            need_from_recent_strain_milli: number | null;
            performance_score: number | null;
            respiratory_rate: number | null;
            score_state: string | null;
            sleep_consistency_percentage: number | null;
            sleep_cycle_count: number | null;
            sleep_debt_milli: number | null;
            sleep_efficiency_percentage: number | null;
            /** Format: date-time */
            start_time: string;
            timezone_offset: Record<string, never> | null;
            total_awake_time_milli: number | null;
            total_in_bed_time_milli: number | null;
            total_light_sleep_time_milli: number | null;
            total_no_data_time_milli: number | null;
            total_rem_sleep_time_milli: number | null;
            total_slow_wave_sleep_time_milli: number | null;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
        };
        "github_com_arvind_whoop-stats_internal_db.SyncStatus": {
            error_message: string | null;
            /** Format: date-time */
            finished_at: string | null;
            /** Format: date-time */
            last_success_at: string | null;
            resource: string;
            /** Format: date-time */
            started_at: string;
            state: string;
            user_id: string;
        };
        "github_com_arvind_whoop-stats_internal_db.Workout": {
            altitude_change_meter: number | null;
            altitude_gain_meter: number | null;
            average_heart_rate: number | null;
            /** Format: date-time */
            created_at: string;
            distance_meter: number | null;
            /** Format: date-time */
            end_time: string | null;
            id: string;
            kilojoule: number | null;
            max_heart_rate: number | null;
            percent_recorded: number | null;
            score_state: string | null;
            sport_id: number | null;
            sport_name: string | null;
            /** Format: date-time */
            start_time: string;
            strain: number | null;
            timezone_offset: Record<string, never> | null;
            /** Format: date-time */
            updated_at: string;
            user_id: string;
            zone_five_milli: number | null;
            zone_four_milli: number | null;
            zone_one_milli: number | null;
            zone_three_milli: number | null;
            zone_two_milli: number | null;
            zone_zero_milli: number | null;
        };
        "internal_api.CyclesPage": {
            next_cursor: string | null;
            records: components["schemas"]["github_com_arvind_whoop-stats_internal_db.Cycle"][];
        };
        "internal_api.ErrorResponse": {
            error: {
                code?: string;
                message?: string;
            };
        };
        "internal_api.RecoveriesPage": {
            next_cursor: string | null;
            records: components["schemas"]["github_com_arvind_whoop-stats_internal_db.GetRecoveriesRow"][];
        };
        "internal_api.SleepsPage": {
            next_cursor: string | null;
            records: components["schemas"]["github_com_arvind_whoop-stats_internal_db.Sleep"][];
        };
        "internal_api.SyncStatusResponse": {
            resources: components["schemas"]["github_com_arvind_whoop-stats_internal_db.SyncStatus"][];
            running: boolean;
        };
        "internal_api.WorkoutsPage": {
            next_cursor: string | null;
            records: components["schemas"]["github_com_arvind_whoop-stats_internal_db.Workout"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
