// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cycles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches cycles using cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cycles"
                ],
                "summary": "Get cycles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Data inicial em Brasília (AAAA-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data final inclusiva em Brasília (AAAA-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor opaco da página anterior",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.CyclesPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/insights": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches daily strain and recovery from continuous aggregates for the last 30 days",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "insights"
                ],
                "summary": "Get insights",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/recoveries": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches recoveries using cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recoveries"
                ],
                "summary": "Get recoveries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Data inicial em Brasília (AAAA-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data final inclusiva em Brasília (AAAA-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor opaco da página anterior",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.RecoveriesPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sleeps": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches sleeps using cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sleeps"
                ],
                "summary": "Get sleeps",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Data inicial em Brasília (AAAA-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data final inclusiva em Brasília (AAAA-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor opaco da página anterior",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SleepsPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Enqueues a background sync job for the authenticated user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "Trigger ad-hoc sync",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sync/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Consultar o estado persistido da sincronização",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SyncStatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/user/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the user profile from the WHOOP API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get basic profile info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workouts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches workouts using cursor-based pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workouts"
                ],
                "summary": "Get workouts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Data inicial em Brasília (AAAA-MM-DD)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Data final inclusiva em Brasília (AAAA-MM-DD)",
                        "name": "end",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Cursor opaco da página anterior",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.WorkoutsPage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_arvind_whoop-stats_internal_db.Cycle": {
            "type": "object",
            "properties": {
                "average_heart_rate": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kilojoule": {
                    "type": "number"
                },
                "max_heart_rate": {
                    "type": "integer"
                },
                "score_state": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "step_count": {
                    "type": "integer"
                },
                "strain": {
                    "type": "number"
                },
                "timezone_offset": {
                    "type": "object"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_arvind_whoop-stats_internal_db.GetRecoveriesRow": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "cycle_end": {
                    "type": "string"
                },
                "cycle_start": {
                    "type": "string"
                },
                "hrv_rmssd_milli": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "recorded_at": {
                    "type": "string"
                },
                "recovery_score": {
                    "type": "number"
                },
                "reference_time": {
                    "type": "string"
                },
                "resting_heart_rate": {
                    "type": "number"
                },
                "score_state": {
                    "type": "string"
                },
                "skin_temp_celsius": {
                    "type": "number"
                },
                "sleep_id": {
                    "type": "string"
                },
                "spo2_percentage": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                },
                "timezone_offset": {
                    "type": "object"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_calibrating": {
                    "type": "boolean"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_arvind_whoop-stats_internal_db.Sleep": {
            "type": "object",
            "properties": {
                "baseline_milli": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "cycle_id": {
                    "type": "integer"
                },
                "disturbance_count": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nap": {
                    "type": "boolean"
                },
                "need_from_recent_nap_milli": {
                    "type": "integer"
                },
                "need_from_recent_strain_milli": {
                    "type": "integer"
                },
                "performance_score": {
                    "type": "number"
                },
                "respiratory_rate": {
                    "type": "number"
                },
                "score_state": {
                    "type": "string"
                },
                "sleep_consistency_percentage": {
                    "type": "number"
                },
                "sleep_cycle_count": {
                    "type": "integer"
                },
                "sleep_debt_milli": {
                    "type": "integer"
                },
                "sleep_efficiency_percentage": {
                    "type": "number"
                },
                "start_time": {
                    "type": "string"
                },
                "timezone_offset": {
                    "type": "object"
                },
                "total_awake_time_milli": {
                    "type": "integer"
                },
                "total_in_bed_time_milli": {
                    "type": "integer"
                },
                "total_light_sleep_time_milli": {
                    "type": "integer"
                },
                "total_no_data_time_milli": {
                    "type": "integer"
                },
                "total_rem_sleep_time_milli": {
                    "type": "integer"
                },
                "total_slow_wave_sleep_time_milli": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_arvind_whoop-stats_internal_db.SyncStatus": {
            "type": "object",
            "properties": {
                "error_message": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "last_success_at": {
                    "type": "string"
                },
                "resource": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_arvind_whoop-stats_internal_db.Workout": {
            "type": "object",
            "properties": {
                "altitude_change_meter": {
                    "type": "number"
                },
                "altitude_gain_meter": {
                    "type": "number"
                },
                "average_heart_rate": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "distance_meter": {
                    "type": "number"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kilojoule": {
                    "type": "number"
                },
                "max_heart_rate": {
                    "type": "integer"
                },
                "percent_recorded": {
                    "type": "number"
                },
                "score_state": {
                    "type": "string"
                },
                "sport_id": {
                    "type": "integer"
                },
                "sport_name": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "strain": {
                    "type": "number"
                },
                "timezone_offset": {
                    "type": "object"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "zone_five_milli": {
                    "type": "integer"
                },
                "zone_four_milli": {
                    "type": "integer"
                },
                "zone_one_milli": {
                    "type": "integer"
                },
                "zone_three_milli": {
                    "type": "integer"
                },
                "zone_two_milli": {
                    "type": "integer"
                },
                "zone_zero_milli": {
                    "type": "integer"
                }
            }
        },
        "internal_api.CyclesPage": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arvind_whoop-stats_internal_db.Cycle"
                    }
                }
            }
        },
        "internal_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        },
                        "message": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "internal_api.RecoveriesPage": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arvind_whoop-stats_internal_db.GetRecoveriesRow"
                    }
                }
            }
        },
        "internal_api.SleepsPage": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arvind_whoop-stats_internal_db.Sleep"
                    }
                }
            }
        },
        "internal_api.SyncStatusResponse": {
            "type": "object",
            "properties": {
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arvind_whoop-stats_internal_db.SyncStatus"
                    }
                },
                "running": {
                    "type": "boolean"
                }
            }
        },
        "internal_api.WorkoutsPage": {
            "type": "object",
            "properties": {
                "next_cursor": {
                    "type": "string"
                },
                "records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_arvind_whoop-stats_internal_db.Workout"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
