// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// User body measurements from /v1/user/measurement/body
type BodyMeasurement struct {
	ID             pgtype.UUID        `json:"id"`
	HeightMeter    pgtype.Float4      `json:"height_meter"`
	WeightKilogram pgtype.Float4      `json:"weight_kilogram"`
	MaxHeartRate   pgtype.Int4        `json:"max_heart_rate"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// WHOOP physiological cycles (typically one per day) with strain scores
type Cycle struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	Strain           pgtype.Float4      `json:"strain"`
	Kilojoule        pgtype.Float4      `json:"kilojoule"`
	AverageHeartRate pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate     pgtype.Int4        `json:"max_heart_rate"`
	ScoreState       pgtype.Text        `json:"score_state"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	StepCount        pgtype.Int4        `json:"step_count"`
}

type DailyRecovery struct {
	UserID      pgtype.UUID     `json:"user_id"`
	Bucket      pgtype.Interval `json:"bucket"`
	AvgRecovery float64         `json:"avg_recovery"`
}

type DailySleep struct {
	UserID         pgtype.UUID     `json:"user_id"`
	Bucket         pgtype.Interval `json:"bucket"`
	AvgPerformance float64         `json:"avg_performance"`
	AvgEfficiency  float64         `json:"avg_efficiency"`
}

type DailyStrain struct {
	UserID    pgtype.UUID     `json:"user_id"`
	Bucket    pgtype.Interval `json:"bucket"`
	AvgStrain float64         `json:"avg_strain"`
	MaxStrain interface{}     `json:"max_strain"`
}

// Daily recovery scores with HRV, RHR, SpO2, and skin temperature
type Recovery struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	RecoveryScore    pgtype.Float4      `json:"recovery_score"`
	RestingHeartRate pgtype.Float4      `json:"resting_heart_rate"`
	HrvRmssdMilli    pgtype.Float4      `json:"hrv_rmssd_milli"`
	Spo2Percentage   pgtype.Float4      `json:"spo2_percentage"`
	SkinTempCelsius  pgtype.Float4      `json:"skin_temp_celsius"`
	SleepID          pgtype.Text        `json:"sleep_id"`
	ScoreState       pgtype.Text        `json:"score_state"`
	UserCalibrating  pgtype.Bool        `json:"user_calibrating"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Sleep sessions with stage breakdowns, sleep need, and debt tracking
type Sleep struct {
	ID                          string             `json:"id"`
	UserID                      pgtype.UUID        `json:"user_id"`
	StartTime                   pgtype.Timestamptz `json:"start_time"`
	EndTime                     pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset              pgtype.Interval    `json:"timezone_offset"`
	PerformanceScore            pgtype.Float4      `json:"performance_score"`
	Nap                         pgtype.Bool        `json:"nap"`
	RespiratoryRate             pgtype.Float4      `json:"respiratory_rate"`
	SleepConsistencyPercentage  pgtype.Float4      `json:"sleep_consistency_percentage"`
	SleepEfficiencyPercentage   pgtype.Float4      `json:"sleep_efficiency_percentage"`
	SleepDebtMilli              pgtype.Int4        `json:"sleep_debt_milli"`
	TotalInBedTimeMilli         pgtype.Int4        `json:"total_in_bed_time_milli"`
	TotalAwakeTimeMilli         pgtype.Int4        `json:"total_awake_time_milli"`
	TotalNoDataTimeMilli        pgtype.Int4        `json:"total_no_data_time_milli"`
	TotalLightSleepTimeMilli    pgtype.Int4        `json:"total_light_sleep_time_milli"`
	TotalSlowWaveSleepTimeMilli pgtype.Int4        `json:"total_slow_wave_sleep_time_milli"`
	TotalRemSleepTimeMilli      pgtype.Int4        `json:"total_rem_sleep_time_milli"`
	SleepCycleCount             pgtype.Int4        `json:"sleep_cycle_count"`
	DisturbanceCount            pgtype.Int4        `json:"disturbance_count"`
	CycleID                     pgtype.Int8        `json:"cycle_id"`
	ScoreState                  pgtype.Text        `json:"score_state"`
	BaselineMilli               pgtype.Int4        `json:"baseline_milli"`
	NeedFromRecentStrainMilli   pgtype.Int4        `json:"need_from_recent_strain_milli"`
	NeedFromRecentNapMilli      pgtype.Int4        `json:"need_from_recent_nap_milli"`
	CreatedAt                   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `json:"updated_at"`
}

type SyncStatus struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Resource      string             `json:"resource"`
	State         string             `json:"state"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
}

// Core user accounts with AES-256-GCM encrypted OAuth2 tokens
type User struct {
	ID                    pgtype.UUID        `json:"id"`
	WhoopUserID           string             `json:"whoop_user_id"`
	EncryptedAccessToken  []byte             `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte             `json:"encrypted_refresh_token"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// WHOOP user profile data (name, email) fetched from /v1/user/profile/basic
type UserProfile struct {
	ID          pgtype.UUID        `json:"id"`
	WhoopUserID int64              `json:"whoop_user_id"`
	Email       pgtype.Text        `json:"email"`
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Webhook inbox: events stored immediately on receipt, processed asynchronously by the background worker
type WebhookEvent struct {
	ID          pgtype.UUID        `json:"id"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	RetryCount  int32              `json:"retry_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type WeeklyRecovery struct {
	UserID      pgtype.UUID     `json:"user_id"`
	Bucket      pgtype.Interval `json:"bucket"`
	AvgRecovery float64         `json:"avg_recovery"`
}

type WeeklyStrain struct {
	UserID    pgtype.UUID     `json:"user_id"`
	Bucket    pgtype.Interval `json:"bucket"`
	AvgStrain float64         `json:"avg_strain"`
	MaxStrain interface{}     `json:"max_strain"`
}

// Workout sessions with HR zones, GPS data, and sport classification
type Workout struct {
	ID                  string             `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset      pgtype.Interval    `json:"timezone_offset"`
	SportID             pgtype.Int4        `json:"sport_id"`
	SportName           pgtype.Text        `json:"sport_name"`
	Strain              pgtype.Float4      `json:"strain"`
	AverageHeartRate    pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate        pgtype.Int4        `json:"max_heart_rate"`
	Kilojoule           pgtype.Float4      `json:"kilojoule"`
	PercentRecorded     pgtype.Float4      `json:"percent_recorded"`
	DistanceMeter       pgtype.Float4      `json:"distance_meter"`
	AltitudeGainMeter   pgtype.Float4      `json:"altitude_gain_meter"`
	AltitudeChangeMeter pgtype.Float4      `json:"altitude_change_meter"`
	ZoneZeroMilli       pgtype.Int4        `json:"zone_zero_milli"`
	ZoneOneMilli        pgtype.Int4        `json:"zone_one_milli"`
	ZoneTwoMilli        pgtype.Int4        `json:"zone_two_milli"`
	ZoneThreeMilli      pgtype.Int4        `json:"zone_three_milli"`
	ZoneFourMilli       pgtype.Int4        `json:"zone_four_milli"`
	ZoneFiveMilli       pgtype.Int4        `json:"zone_five_milli"`
	ScoreState          pgtype.Text        `json:"score_state"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
