// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one

INSERT INTO webhook_events (payload, status, created_at)
VALUES ($1, $2, NOW())
RETURNING id, payload, status, retry_count, created_at, processed_at
`

type CreateWebhookEventParams struct {
	Payload []byte `json:"payload"`
	Status  string `json:"status"`
}

// ---------------------------------------------------------------------------
// Webhook Events
// ---------------------------------------------------------------------------
func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent, arg.Payload, arg.Status)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getCycles = `-- name: GetCycles :many
SELECT id, user_id, start_time, end_time, timezone_offset, strain, kilojoule, average_heart_rate, max_heart_rate, score_state, created_at, updated_at, step_count FROM cycles
WHERE user_id = $1
AND start_time < $2::timestamptz
AND (end_time IS NULL OR end_time > $3::timestamptz)
AND (start_time < $4::timestamptz OR (start_time = $4::timestamptz AND id::text < $5::text))
ORDER BY start_time DESC, id::text DESC
LIMIT $6
`

type GetCyclesParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    string             `json:"cursor_id"`
	PageLimit   int32              `json:"page_limit"`
}

func (q *Queries) GetCycles(ctx context.Context, arg GetCyclesParams) ([]Cycle, error) {
	rows, err := q.db.Query(ctx, getCycles,
		arg.UserID,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cycle{}
	for rows.Next() {
		var i Cycle
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.Strain,
			&i.Kilojoule,
			&i.AverageHeartRate,
			&i.MaxHeartRate,
			&i.ScoreState,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StepCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyRecovery = `-- name: GetDailyRecovery :many
SELECT user_id, bucket, avg_recovery FROM daily_recovery
WHERE user_id = $1 AND bucket >= $2::timestamptz
ORDER BY bucket ASC
`

type GetDailyRecoveryParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) GetDailyRecovery(ctx context.Context, arg GetDailyRecoveryParams) ([]DailyRecovery, error) {
	rows, err := q.db.Query(ctx, getDailyRecovery, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyRecovery{}
	for rows.Next() {
		var i DailyRecovery
		if err := rows.Scan(&i.UserID, &i.Bucket, &i.AvgRecovery); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailySleep = `-- name: GetDailySleep :many
SELECT user_id, bucket, avg_performance, avg_efficiency FROM daily_sleep
WHERE user_id = $1 AND bucket >= $2::timestamptz
ORDER BY bucket ASC
`

type GetDailySleepParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

func (q *Queries) GetDailySleep(ctx context.Context, arg GetDailySleepParams) ([]DailySleep, error) {
	rows, err := q.db.Query(ctx, getDailySleep, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySleep{}
	for rows.Next() {
		var i DailySleep
		if err := rows.Scan(
			&i.UserID,
			&i.Bucket,
			&i.AvgPerformance,
			&i.AvgEfficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyStrain = `-- name: GetDailyStrain :many

SELECT user_id, bucket, avg_strain, max_strain FROM daily_strain
WHERE user_id = $1 AND bucket >= $2::timestamptz
ORDER BY bucket ASC
`

type GetDailyStrainParams struct {
	UserID pgtype.UUID        `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

// ---------------------------------------------------------------------------
// Continuous Aggregate Queries (dashboard insights)
// ---------------------------------------------------------------------------
func (q *Queries) GetDailyStrain(ctx context.Context, arg GetDailyStrainParams) ([]DailyStrain, error) {
	rows, err := q.db.Query(ctx, getDailyStrain, arg.UserID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStrain{}
	for rows.Next() {
		var i DailyStrain
		if err := rows.Scan(
			&i.UserID,
			&i.Bucket,
			&i.AvgStrain,
			&i.MaxStrain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWebhookEvents = `-- name: GetPendingWebhookEvents :many
SELECT id, payload, status, retry_count, created_at, processed_at FROM webhook_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingWebhookEvents(ctx context.Context, limit int32) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecoveries = `-- name: GetRecoveries :many
SELECT r.id, r.user_id, r.start_time, r.timezone_offset, r.recovery_score, r.resting_heart_rate, r.hrv_rmssd_milli, r.spo2_percentage, r.skin_temp_celsius, r.sleep_id, r.score_state, r.user_calibrating, r.created_at, r.updated_at, r.start_time AS recorded_at, s.end_time AS reference_time, c.start_time AS cycle_start, c.end_time AS cycle_end
FROM recoveries r
LEFT JOIN sleeps s ON s.id = r.sleep_id AND s.user_id = r.user_id
LEFT JOIN cycles c ON c.id = r.id AND c.user_id = r.user_id
WHERE r.user_id = $1
AND ((COALESCE(s.end_time, r.start_time) >= $2::timestamptz AND COALESCE(s.end_time, r.start_time) < $3::timestamptz)
 OR (c.start_time < $3::timestamptz AND (c.end_time IS NULL OR c.end_time > $2::timestamptz)))
AND (r.start_time < $4::timestamptz OR (r.start_time = $4::timestamptz AND r.id::text < $5::text))
ORDER BY r.start_time DESC, r.id::text DESC
LIMIT $6
`

type GetRecoveriesParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    string             `json:"cursor_id"`
	PageLimit   int32              `json:"page_limit"`
}

type GetRecoveriesRow struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	RecoveryScore    pgtype.Float4      `json:"recovery_score"`
	RestingHeartRate pgtype.Float4      `json:"resting_heart_rate"`
	HrvRmssdMilli    pgtype.Float4      `json:"hrv_rmssd_milli"`
	Spo2Percentage   pgtype.Float4      `json:"spo2_percentage"`
	SkinTempCelsius  pgtype.Float4      `json:"skin_temp_celsius"`
	SleepID          pgtype.Text        `json:"sleep_id"`
	ScoreState       pgtype.Text        `json:"score_state"`
	UserCalibrating  pgtype.Bool        `json:"user_calibrating"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RecordedAt       pgtype.Timestamptz `json:"recorded_at"`
	ReferenceTime    pgtype.Timestamptz `json:"reference_time"`
	CycleStart       pgtype.Timestamptz `json:"cycle_start"`
	CycleEnd         pgtype.Timestamptz `json:"cycle_end"`
}

func (q *Queries) GetRecoveries(ctx context.Context, arg GetRecoveriesParams) ([]GetRecoveriesRow, error) {
	rows, err := q.db.Query(ctx, getRecoveries,
		arg.UserID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecoveriesRow{}
	for rows.Next() {
		var i GetRecoveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.TimezoneOffset,
			&i.RecoveryScore,
			&i.RestingHeartRate,
			&i.HrvRmssdMilli,
			&i.Spo2Percentage,
			&i.SkinTempCelsius,
			&i.SleepID,
			&i.ScoreState,
			&i.UserCalibrating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RecordedAt,
			&i.ReferenceTime,
			&i.CycleStart,
			&i.CycleEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSleeps = `-- name: GetSleeps :many
SELECT id, user_id, start_time, end_time, timezone_offset, performance_score, nap, respiratory_rate, sleep_consistency_percentage, sleep_efficiency_percentage, sleep_debt_milli, total_in_bed_time_milli, total_awake_time_milli, total_no_data_time_milli, total_light_sleep_time_milli, total_slow_wave_sleep_time_milli, total_rem_sleep_time_milli, sleep_cycle_count, disturbance_count, cycle_id, score_state, baseline_milli, need_from_recent_strain_milli, need_from_recent_nap_milli, created_at, updated_at FROM sleeps
WHERE user_id = $1
AND end_time >= $2::timestamptz
AND end_time < $3::timestamptz
AND (start_time < $4::timestamptz OR (start_time = $4::timestamptz AND id::text < $5::text))
ORDER BY start_time DESC, id::text DESC
LIMIT $6
`

type GetSleepsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    string             `json:"cursor_id"`
	PageLimit   int32              `json:"page_limit"`
}

func (q *Queries) GetSleeps(ctx context.Context, arg GetSleepsParams) ([]Sleep, error) {
	rows, err := q.db.Query(ctx, getSleeps,
		arg.UserID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sleep{}
	for rows.Next() {
		var i Sleep
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.PerformanceScore,
			&i.Nap,
			&i.RespiratoryRate,
			&i.SleepConsistencyPercentage,
			&i.SleepEfficiencyPercentage,
			&i.SleepDebtMilli,
			&i.TotalInBedTimeMilli,
			&i.TotalAwakeTimeMilli,
			&i.TotalNoDataTimeMilli,
			&i.TotalLightSleepTimeMilli,
			&i.TotalSlowWaveSleepTimeMilli,
			&i.TotalRemSleepTimeMilli,
			&i.SleepCycleCount,
			&i.DisturbanceCount,
			&i.CycleID,
			&i.ScoreState,
			&i.BaselineMilli,
			&i.NeedFromRecentStrainMilli,
			&i.NeedFromRecentNapMilli,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSyncStatus = `-- name: GetSyncStatus :many
SELECT user_id, resource, state, started_at, finished_at, last_success_at, error_message FROM sync_status WHERE user_id = $1 ORDER BY resource
`

func (q *Queries) GetSyncStatus(ctx context.Context, userID pgtype.UUID) ([]SyncStatus, error) {
	rows, err := q.db.Query(ctx, getSyncStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SyncStatus{}
	for rows.Next() {
		var i SyncStatus
		if err := rows.Scan(
			&i.UserID,
			&i.Resource,
			&i.State,
			&i.StartedAt,
			&i.FinishedAt,
			&i.LastSuccessAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWhoopID = `-- name: GetUserByWhoopID :one
SELECT id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at FROM users
WHERE whoop_user_id = $1 LIMIT 1
`

func (q *Queries) GetUserByWhoopID(ctx context.Context, whoopUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWhoopID, whoopUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, whoop_user_id, email, first_name, last_name, created_at, updated_at FROM user_profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserProfile(ctx context.Context, id pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkouts = `-- name: GetWorkouts :many
SELECT id, user_id, start_time, end_time, timezone_offset, sport_id, sport_name, strain, average_heart_rate, max_heart_rate, kilojoule, percent_recorded, distance_meter, altitude_gain_meter, altitude_change_meter, zone_zero_milli, zone_one_milli, zone_two_milli, zone_three_milli, zone_four_milli, zone_five_milli, score_state, created_at, updated_at FROM workouts
WHERE user_id = $1
AND start_time < $2::timestamptz
AND (end_time IS NULL OR end_time > $3::timestamptz)
AND (start_time < $4::timestamptz OR (start_time = $4::timestamptz AND id::text < $5::text))
ORDER BY start_time DESC, id::text DESC
LIMIT $6
`

type GetWorkoutsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    string             `json:"cursor_id"`
	PageLimit   int32              `json:"page_limit"`
}

func (q *Queries) GetWorkouts(ctx context.Context, arg GetWorkoutsParams) ([]Workout, error) {
	rows, err := q.db.Query(ctx, getWorkouts,
		arg.UserID,
		arg.PeriodEnd,
		arg.PeriodStart,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workout{}
	for rows.Next() {
		var i Workout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartTime,
			&i.EndTime,
			&i.TimezoneOffset,
			&i.SportID,
			&i.SportName,
			&i.Strain,
			&i.AverageHeartRate,
			&i.MaxHeartRate,
			&i.Kilojoule,
			&i.PercentRecorded,
			&i.DistanceMeter,
			&i.AltitudeGainMeter,
			&i.AltitudeChangeMeter,
			&i.ZoneZeroMilli,
			&i.ZoneOneMilli,
			&i.ZoneTwoMilli,
			&i.ZoneThreeMilli,
			&i.ZoneFourMilli,
			&i.ZoneFiveMilli,
			&i.ScoreState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const interruptSyncStatus = `-- name: InterruptSyncStatus :exec
UPDATE sync_status SET state = 'interrupted', finished_at = NOW(), error_message = 'Atualização interrompida; tente novamente.' WHERE state = 'running'
`

func (q *Queries) InterruptSyncStatus(ctx context.Context) error {
	_, err := q.db.Exec(ctx, interruptSyncStatus)
	return err
}

const setSyncStatus = `-- name: SetSyncStatus :exec
INSERT INTO sync_status (user_id, resource, state, started_at, finished_at, last_success_at, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, resource) DO UPDATE SET
 state = EXCLUDED.state, started_at = EXCLUDED.started_at, finished_at = EXCLUDED.finished_at,
 last_success_at = COALESCE(EXCLUDED.last_success_at, sync_status.last_success_at), error_message = EXCLUDED.error_message
`

type SetSyncStatusParams struct {
	UserID        pgtype.UUID        `json:"user_id"`
	Resource      string             `json:"resource"`
	State         string             `json:"state"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	LastSuccessAt pgtype.Timestamptz `json:"last_success_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
}

func (q *Queries) SetSyncStatus(ctx context.Context, arg SetSyncStatusParams) error {
	_, err := q.db.Exec(ctx, setSyncStatus,
		arg.UserID,
		arg.Resource,
		arg.State,
		arg.StartedAt,
		arg.FinishedAt,
		arg.LastSuccessAt,
		arg.ErrorMessage,
	)
	return err
}

const updateWebhookEventStatus = `-- name: UpdateWebhookEventStatus :exec
UPDATE webhook_events
SET status = $2, processed_at = NOW()
WHERE id = $1
`

type UpdateWebhookEventStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateWebhookEventStatus(ctx context.Context, arg UpdateWebhookEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEventStatus, arg.ID, arg.Status)
	return err
}

const updateWebhookEventStatuses = `-- name: UpdateWebhookEventStatuses :exec
UPDATE webhook_events
SET status = $1, processed_at = NOW()
WHERE id = ANY($2::uuid[])
`

type UpdateWebhookEventStatusesParams struct {
	Status   string        `json:"status"`
	EventIds []pgtype.UUID `json:"event_ids"`
}

func (q *Queries) UpdateWebhookEventStatuses(ctx context.Context, arg UpdateWebhookEventStatusesParams) error {
	_, err := q.db.Exec(ctx, updateWebhookEventStatuses, arg.Status, arg.EventIds)
	return err
}

const upsertBodyMeasurement = `-- name: UpsertBodyMeasurement :exec
INSERT INTO body_measurements (id, height_meter, weight_kilogram, max_heart_rate, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    height_meter = EXCLUDED.height_meter,
    weight_kilogram = EXCLUDED.weight_kilogram,
    max_heart_rate = EXCLUDED.max_heart_rate,
    updated_at = EXCLUDED.updated_at
`

type UpsertBodyMeasurementParams struct {
	ID             pgtype.UUID        `json:"id"`
	HeightMeter    pgtype.Float4      `json:"height_meter"`
	WeightKilogram pgtype.Float4      `json:"weight_kilogram"`
	MaxHeartRate   pgtype.Int4        `json:"max_heart_rate"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertBodyMeasurement(ctx context.Context, arg UpsertBodyMeasurementParams) error {
	_, err := q.db.Exec(ctx, upsertBodyMeasurement,
		arg.ID,
		arg.HeightMeter,
		arg.WeightKilogram,
		arg.MaxHeartRate,
		arg.UpdatedAt,
	)
	return err
}

const upsertCycle = `-- name: UpsertCycle :exec

INSERT INTO cycles (id, user_id, start_time, end_time, timezone_offset, strain, kilojoule, average_heart_rate, max_heart_rate, score_state, step_count, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    strain = EXCLUDED.strain,
    kilojoule = EXCLUDED.kilojoule,
    average_heart_rate = EXCLUDED.average_heart_rate,
    max_heart_rate = EXCLUDED.max_heart_rate,
    score_state = EXCLUDED.score_state,
    step_count = EXCLUDED.step_count,
    updated_at = NOW()
`

type UpsertCycleParams struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	EndTime          pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	Strain           pgtype.Float4      `json:"strain"`
	Kilojoule        pgtype.Float4      `json:"kilojoule"`
	AverageHeartRate pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate     pgtype.Int4        `json:"max_heart_rate"`
	ScoreState       pgtype.Text        `json:"score_state"`
	StepCount        pgtype.Int4        `json:"step_count"`
}

// ---------------------------------------------------------------------------
// Cycles (daily physiological cycles with strain)
// ---------------------------------------------------------------------------
func (q *Queries) UpsertCycle(ctx context.Context, arg UpsertCycleParams) error {
	_, err := q.db.Exec(ctx, upsertCycle,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.Strain,
		arg.Kilojoule,
		arg.AverageHeartRate,
		arg.MaxHeartRate,
		arg.ScoreState,
		arg.StepCount,
	)
	return err
}

const upsertRecovery = `-- name: UpsertRecovery :exec

INSERT INTO recoveries (id, user_id, start_time, timezone_offset, recovery_score, resting_heart_rate, hrv_rmssd_milli, spo2_percentage, skin_temp_celsius, sleep_id, score_state, user_calibrating, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    timezone_offset = EXCLUDED.timezone_offset,
    recovery_score = EXCLUDED.recovery_score,
    resting_heart_rate = EXCLUDED.resting_heart_rate,
    hrv_rmssd_milli = EXCLUDED.hrv_rmssd_milli,
    spo2_percentage = EXCLUDED.spo2_percentage,
    skin_temp_celsius = EXCLUDED.skin_temp_celsius,
    sleep_id = EXCLUDED.sleep_id,
    score_state = EXCLUDED.score_state,
    user_calibrating = EXCLUDED.user_calibrating,
    updated_at = NOW()
`

type UpsertRecoveryParams struct {
	ID               int64              `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	StartTime        pgtype.Timestamptz `json:"start_time"`
	TimezoneOffset   pgtype.Interval    `json:"timezone_offset"`
	RecoveryScore    pgtype.Float4      `json:"recovery_score"`
	RestingHeartRate pgtype.Float4      `json:"resting_heart_rate"`
	HrvRmssdMilli    pgtype.Float4      `json:"hrv_rmssd_milli"`
	Spo2Percentage   pgtype.Float4      `json:"spo2_percentage"`
	SkinTempCelsius  pgtype.Float4      `json:"skin_temp_celsius"`
	SleepID          pgtype.Text        `json:"sleep_id"`
	ScoreState       pgtype.Text        `json:"score_state"`
	UserCalibrating  pgtype.Bool        `json:"user_calibrating"`
}

// ---------------------------------------------------------------------------
// Recoveries (daily recovery with HRV, RHR, SpO2, skin temp)
// ---------------------------------------------------------------------------
func (q *Queries) UpsertRecovery(ctx context.Context, arg UpsertRecoveryParams) error {
	_, err := q.db.Exec(ctx, upsertRecovery,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.TimezoneOffset,
		arg.RecoveryScore,
		arg.RestingHeartRate,
		arg.HrvRmssdMilli,
		arg.Spo2Percentage,
		arg.SkinTempCelsius,
		arg.SleepID,
		arg.ScoreState,
		arg.UserCalibrating,
	)
	return err
}

const upsertSleep = `-- name: UpsertSleep :exec

INSERT INTO sleeps (id, user_id, start_time, end_time, timezone_offset, performance_score, nap, respiratory_rate, sleep_consistency_percentage, sleep_efficiency_percentage, sleep_debt_milli, total_in_bed_time_milli, total_awake_time_milli, total_no_data_time_milli, total_light_sleep_time_milli, total_slow_wave_sleep_time_milli, total_rem_sleep_time_milli, sleep_cycle_count, disturbance_count, cycle_id, score_state, baseline_milli, need_from_recent_strain_milli, need_from_recent_nap_milli, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    performance_score = EXCLUDED.performance_score,
    nap = EXCLUDED.nap,
    respiratory_rate = EXCLUDED.respiratory_rate,
    sleep_consistency_percentage = EXCLUDED.sleep_consistency_percentage,
    sleep_efficiency_percentage = EXCLUDED.sleep_efficiency_percentage,
    sleep_debt_milli = EXCLUDED.sleep_debt_milli,
    total_in_bed_time_milli = EXCLUDED.total_in_bed_time_milli,
    total_awake_time_milli = EXCLUDED.total_awake_time_milli,
    total_no_data_time_milli = EXCLUDED.total_no_data_time_milli,
    total_light_sleep_time_milli = EXCLUDED.total_light_sleep_time_milli,
    total_slow_wave_sleep_time_milli = EXCLUDED.total_slow_wave_sleep_time_milli,
    total_rem_sleep_time_milli = EXCLUDED.total_rem_sleep_time_milli,
    sleep_cycle_count = EXCLUDED.sleep_cycle_count,
    disturbance_count = EXCLUDED.disturbance_count,
    cycle_id = EXCLUDED.cycle_id,
    score_state = EXCLUDED.score_state,
    baseline_milli = EXCLUDED.baseline_milli,
    need_from_recent_strain_milli = EXCLUDED.need_from_recent_strain_milli,
    need_from_recent_nap_milli = EXCLUDED.need_from_recent_nap_milli,
    updated_at = NOW()
`

type UpsertSleepParams struct {
	ID                          string             `json:"id"`
	UserID                      pgtype.UUID        `json:"user_id"`
	StartTime                   pgtype.Timestamptz `json:"start_time"`
	EndTime                     pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset              pgtype.Interval    `json:"timezone_offset"`
	PerformanceScore            pgtype.Float4      `json:"performance_score"`
	Nap                         pgtype.Bool        `json:"nap"`
	RespiratoryRate             pgtype.Float4      `json:"respiratory_rate"`
	SleepConsistencyPercentage  pgtype.Float4      `json:"sleep_consistency_percentage"`
	SleepEfficiencyPercentage   pgtype.Float4      `json:"sleep_efficiency_percentage"`
	SleepDebtMilli              pgtype.Int4        `json:"sleep_debt_milli"`
	TotalInBedTimeMilli         pgtype.Int4        `json:"total_in_bed_time_milli"`
	TotalAwakeTimeMilli         pgtype.Int4        `json:"total_awake_time_milli"`
	TotalNoDataTimeMilli        pgtype.Int4        `json:"total_no_data_time_milli"`
	TotalLightSleepTimeMilli    pgtype.Int4        `json:"total_light_sleep_time_milli"`
	TotalSlowWaveSleepTimeMilli pgtype.Int4        `json:"total_slow_wave_sleep_time_milli"`
	TotalRemSleepTimeMilli      pgtype.Int4        `json:"total_rem_sleep_time_milli"`
	SleepCycleCount             pgtype.Int4        `json:"sleep_cycle_count"`
	DisturbanceCount            pgtype.Int4        `json:"disturbance_count"`
	CycleID                     pgtype.Int8        `json:"cycle_id"`
	ScoreState                  pgtype.Text        `json:"score_state"`
	BaselineMilli               pgtype.Int4        `json:"baseline_milli"`
	NeedFromRecentStrainMilli   pgtype.Int4        `json:"need_from_recent_strain_milli"`
	NeedFromRecentNapMilli      pgtype.Int4        `json:"need_from_recent_nap_milli"`
}

// ---------------------------------------------------------------------------
// Sleeps (sessions with stage breakdowns and sleep need)
// ---------------------------------------------------------------------------
func (q *Queries) UpsertSleep(ctx context.Context, arg UpsertSleepParams) error {
	_, err := q.db.Exec(ctx, upsertSleep,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.PerformanceScore,
		arg.Nap,
		arg.RespiratoryRate,
		arg.SleepConsistencyPercentage,
		arg.SleepEfficiencyPercentage,
		arg.SleepDebtMilli,
		arg.TotalInBedTimeMilli,
		arg.TotalAwakeTimeMilli,
		arg.TotalNoDataTimeMilli,
		arg.TotalLightSleepTimeMilli,
		arg.TotalSlowWaveSleepTimeMilli,
		arg.TotalRemSleepTimeMilli,
		arg.SleepCycleCount,
		arg.DisturbanceCount,
		arg.CycleID,
		arg.ScoreState,
		arg.BaselineMilli,
		arg.NeedFromRecentStrainMilli,
		arg.NeedFromRecentNapMilli,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :one


INSERT INTO users (whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (whoop_user_id) DO UPDATE SET
    encrypted_access_token = EXCLUDED.encrypted_access_token,
    encrypted_refresh_token = EXCLUDED.encrypted_refresh_token,
    updated_at = NOW()
RETURNING id, whoop_user_id, encrypted_access_token, encrypted_refresh_token, created_at, updated_at
`

type UpsertUserParams struct {
	WhoopUserID           string `json:"whoop_user_id"`
	EncryptedAccessToken  []byte `json:"encrypted_access_token"`
	EncryptedRefreshToken []byte `json:"encrypted_refresh_token"`
}

// =============================================================================
// WHOOP Stats — SQL Queries (sqlc)
// =============================================================================
// These queries are compiled by sqlc into type-safe Go code.
// See sqlc.yaml for configuration.
// =============================================================================
// ---------------------------------------------------------------------------
// Users & Authentication
// ---------------------------------------------------------------------------
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.WhoopUserID, arg.EncryptedAccessToken, arg.EncryptedRefreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WhoopUserID,
		&i.EncryptedAccessToken,
		&i.EncryptedRefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec

INSERT INTO user_profiles (id, whoop_user_id, email, first_name, last_name, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET
    whoop_user_id = EXCLUDED.whoop_user_id,
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    updated_at = EXCLUDED.updated_at
`

type UpsertUserProfileParams struct {
	ID          pgtype.UUID        `json:"id"`
	WhoopUserID int64              `json:"whoop_user_id"`
	Email       pgtype.Text        `json:"email"`
	FirstName   pgtype.Text        `json:"first_name"`
	LastName    pgtype.Text        `json:"last_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// ---------------------------------------------------------------------------
// User Profile & Body Measurements
// ---------------------------------------------------------------------------
func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile,
		arg.ID,
		arg.WhoopUserID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertWorkout = `-- name: UpsertWorkout :exec

INSERT INTO workouts (id, user_id, start_time, end_time, timezone_offset, sport_id, strain, average_heart_rate, max_heart_rate, kilojoule, percent_recorded, distance_meter, altitude_gain_meter, altitude_change_meter, zone_zero_milli, zone_one_milli, zone_two_milli, zone_three_milli, zone_four_milli, zone_five_milli, sport_name, score_state, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, NOW(), NOW())
ON CONFLICT (id, start_time) DO UPDATE SET
    end_time = EXCLUDED.end_time,
    timezone_offset = EXCLUDED.timezone_offset,
    sport_id = EXCLUDED.sport_id,
    strain = EXCLUDED.strain,
    average_heart_rate = EXCLUDED.average_heart_rate,
    max_heart_rate = EXCLUDED.max_heart_rate,
    kilojoule = EXCLUDED.kilojoule,
    percent_recorded = EXCLUDED.percent_recorded,
    distance_meter = EXCLUDED.distance_meter,
    altitude_gain_meter = EXCLUDED.altitude_gain_meter,
    altitude_change_meter = EXCLUDED.altitude_change_meter,
    zone_zero_milli = EXCLUDED.zone_zero_milli,
    zone_one_milli = EXCLUDED.zone_one_milli,
    zone_two_milli = EXCLUDED.zone_two_milli,
    zone_three_milli = EXCLUDED.zone_three_milli,
    zone_four_milli = EXCLUDED.zone_four_milli,
    zone_five_milli = EXCLUDED.zone_five_milli,
    sport_name = EXCLUDED.sport_name,
    score_state = EXCLUDED.score_state,
    updated_at = NOW()
`

type UpsertWorkoutParams struct {
	ID                  string             `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	StartTime           pgtype.Timestamptz `json:"start_time"`
	EndTime             pgtype.Timestamptz `json:"end_time"`
	TimezoneOffset      pgtype.Interval    `json:"timezone_offset"`
	SportID             pgtype.Int4        `json:"sport_id"`
	Strain              pgtype.Float4      `json:"strain"`
	AverageHeartRate    pgtype.Int4        `json:"average_heart_rate"`
	MaxHeartRate        pgtype.Int4        `json:"max_heart_rate"`
	Kilojoule           pgtype.Float4      `json:"kilojoule"`
	PercentRecorded     pgtype.Float4      `json:"percent_recorded"`
	DistanceMeter       pgtype.Float4      `json:"distance_meter"`
	AltitudeGainMeter   pgtype.Float4      `json:"altitude_gain_meter"`
	AltitudeChangeMeter pgtype.Float4      `json:"altitude_change_meter"`
	ZoneZeroMilli       pgtype.Int4        `json:"zone_zero_milli"`
	ZoneOneMilli        pgtype.Int4        `json:"zone_one_milli"`
	ZoneTwoMilli        pgtype.Int4        `json:"zone_two_milli"`
	ZoneThreeMilli      pgtype.Int4        `json:"zone_three_milli"`
	ZoneFourMilli       pgtype.Int4        `json:"zone_four_milli"`
	ZoneFiveMilli       pgtype.Int4        `json:"zone_five_milli"`
	SportName           pgtype.Text        `json:"sport_name"`
	ScoreState          pgtype.Text        `json:"score_state"`
}

// ---------------------------------------------------------------------------
// Workouts (sessions with HR zones, GPS data, sport classification)
// ---------------------------------------------------------------------------
func (q *Queries) UpsertWorkout(ctx context.Context, arg UpsertWorkoutParams) error {
	_, err := q.db.Exec(ctx, upsertWorkout,
		arg.ID,
		arg.UserID,
		arg.StartTime,
		arg.EndTime,
		arg.TimezoneOffset,
		arg.SportID,
		arg.Strain,
		arg.AverageHeartRate,
		arg.MaxHeartRate,
		arg.Kilojoule,
		arg.PercentRecorded,
		arg.DistanceMeter,
		arg.AltitudeGainMeter,
		arg.AltitudeChangeMeter,
		arg.ZoneZeroMilli,
		arg.ZoneOneMilli,
		arg.ZoneTwoMilli,
		arg.ZoneThreeMilli,
		arg.ZoneFourMilli,
		arg.ZoneFiveMilli,
		arg.SportName,
		arg.ScoreState,
	)
	return err
}
